server:
  port: 8501
spring:
  application:
    name: zkclient
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0 #设置为1（默认为0.1），否则要调用10次才会上传成功1次
    trace-id128: true
