server:
  port: 8400
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: cs
  cloud:
    config:
      server:
        git:
          uri: https://github.com/  # 配置git仓库的地址
          search-paths: repo  # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: # git仓库的账号
          password:  # git仓库的密码
#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh