spring:
  application:
    name: bus
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8402
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
