server:
  port: 8900

spring:
  application:
    name: hd

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: ["health","info","hystrix.stream"]
      cors:
        allowed-origins: "*"
allowed-methods: "*"